"""next migrate_4

Revision ID: 116653581b6c
Revises: 83b097ab4f93
Create Date: 2020-11-06 11:22:33.065988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116653581b6c'
down_revision = '83b097ab4f93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
