"""next migrate_5

Revision ID: 83b097ab4f93
Revises: 988a15a692af
Create Date: 2020-11-06 11:21:30.315586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b097ab4f93'
down_revision = '988a15a692af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
