"""next migrate_4

Revision ID: 988a15a692af
Revises: f3442d2f3197
Create Date: 2020-11-06 11:15:56.705212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988a15a692af'
down_revision = 'f3442d2f3197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
